---
# tasks file for nginx

- name: Install nginx packages
  ansible.builtin.package:
    name: "{{ nginx_packages }}"
    state: present

- name: Enable nginx service
  ansible.builtin.service:
    name: "nginx"
    enabled: true
    state: started

- name: Perform level 1 actions
  ansible.builtin.import_tasks: level1actions.yml

- name: Perform level 2 actions
  ansible.builtin.import_tasks: level2actions.yml
