---
# tasks file for nginx

- name: Install nginx packages
  package:
    name: "{{ nginx_packages }}"
    state: present

- name: Enable nginx service
  service:
    name: "nginx"
    enabled: true
    state: started

- name: Perform level 1 actions
  import_tasks: level1actions.yml

- name: Perform level 2 actions
  import_tasks: level2actions.yml
