---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Create directories if they do not exist
    file:
      name: /usr/share/nginx/html
      state: directory
      mode: 0755
      recurse: yes

  - name: Check if index.html is a link
    stat:
      path: /usr/share/nginx/html/index.html
    register: nginx_cmd_result

  - name: Remove index.html if it is a link
    file:
      path: /usr/share/nginx/html/index.html
      state: absent
    when: nginx_cmd_result.stat.islnk is defined and nginx_cmd_result.stat.islnk

  - name: Ensure index.html exists so test works
    file:
      path: /usr/share/nginx/html/index.html
      state: touch
      modification_time: preserve
      access_time: preserve
      follow: true
      mode: 0644

  - name: add index.html on centos 7 to prevent test error
    shell: |
      cat <<EOF > /usr/share/nginx/html/index.html
      <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
      <html>
      <head>
        <title>NGINX TEST</title>
      </head>
      <body>
      <h1>Working...</h1>
      </body>
      </html>
      EOF
    changed_when: false

  - name: Check if nginx is listening on port 80
    uri:
      url: http://localhost/
      status_code: 200
